services:
  - type: web
    name: jiabamap-api
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: API_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_PROJECT_ID
        sync: false
      - key: BUCKET_NAME
        sync: false
      - key: GOOGLE_CLOUD_STORAGE_BASE_URL
        sync: false
      - key: FRONTEND_URLS
        sync: false
      - key: CHANNEL_ID
        sync: false
      - key: CHANNEL_SECRET
        sync: false
      - key: LINE_PAY_API_URL
        value: https://sandbox-api-pay.line.me
      - key: BACKEND_NGROK_URL
        sync: false
      - key: GOOGLE_CREDENTIALS_JSON
        sync: false
